name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # If you have any tests, run them here
        echo "No tests defined"  # Replace with actual test commands if available

    - name: Package the application
      run: |
        # Create a zip file of the application for deployment
        zip -r app.zip . -x ".git/*" -x "__pycache__/*" -x "app.zip"

    - name: Upload to S3
      uses: aws-actions/aws-cli-action@v1
      with:
        args: s3 cp app.zip s3://your-s3-bucket-name/app.zip  # Upload the package to an S3 bucket
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'your-aws-region'  # Replace with your AWS region

    - name: Deploy to EC2
      run: |
        # Connect to your EC2 instance and deploy the application
        ssh -o StrictHostKeyChecking=no -i /path/to/your-key.pem ec2-user@your-ec2-instance-ip << 'EOF'
          # Download the package from S3
          aws s3 cp s3://your-s3-bucket-name/app.zip /home/ec2-user/
          
          # Unzip the package
          unzip /home/ec2-user/app.zip -d /home/ec2-user/app
          
          # Navigate to the application directory
          cd /home/ec2-user/app
          
          # Install dependencies
          pip install -r requirements.txt
          
          # Restart the FastAPI service (modify based on your setup)
          sudo systemctl restart fastapi-app  # Replace with your service name
        EOF
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'your-aws-region'  # Replace with your AWS region

    # For the assignment, the FastAPI application was deployed using the management console on AWS EC2. This workflow is included
    # to demonstrate CI/CD concepts with GitHub Actions.
